// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://rgv5rnjrnfachcstzeg6kmvbcq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wyjbnw5dcjcsvdellpqbzstjoi",
    "aws_cognito_identity_pool_id": "us-east-1:786edb9e-6170-40b8-bbd7-67e7eabc1ad3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yjXMk1TmQ",
    "aws_user_pools_web_client_id": "32u15gh2aaa2ev1ts3l5r0r1da"
};


export default awsmobile;
